[package]
name = "box_photo_geo_url_rs"
version = "0.1.0"
description = "Box Photo Geo URL Tauri App"
authors = ["you"]
edition = "2021"

[lib]
name = "box_photo_geo_url_rs_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.37", features = ["full"] }
csv = "1.3"
regex = "1.10"
kamadak-exif = "0.5"
futures = "0.3"
dirs = "5.0"
anyhow = "1.0.104"
